Pull Request created
Petliuk/book.project pull request #1
Opened 2024-12-19 19:42 UTC by Petliuk

2024-12-20 07:32 UTC, liliia-ponomarenko requested changes
Good job! Let’s complete your solution ;)

2024-12-20 07:32 UTC, liliia-ponomarenko commented on pom.xml
> +    <groupId>mate.academy</groupId>
Don’t  use mate.academy in your project

2024-12-20 07:32 UTC, liliia-ponomarenko commented on pom.xml
> +    <description>into</description>
add checkstyle plugin and setup ci-cd

2024-12-20 07:32 UTC, liliia-ponomarenko commented on src/main/java/com/example/mate_academy/controller/BookController.java
> +
```suggestion
```

2024-12-20 07:32 UTC, liliia-ponomarenko commented on src/main/java/com/example/mate_academy/controller/BookController.java
> +public class BookController {
Your task doesn't include web implementation. Let's follow the task requirements.

2024-12-20 07:32 UTC, liliia-ponomarenko commented on src/main/java/com/example/mate_academy/model/Book.java
> +
Not full entity fields

2024-12-20 07:32 UTC, liliia-ponomarenko commented on src/test/resources/application.properties
> +spring.datasource.url=jdbc:mysql://localhost:3306/db?serverTimezone=UTC
Let’s  use h2 for test configuration

2024-12-21 14:46 UTC, sarakhmen approved these changes

2024-12-24 14:59 UTC, merged